[2022-02-19 09:25:21,099] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_transform 2022-02-19T09:25:19.936863+00:00 [queued]>
[2022-02-19 09:25:21,129] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: 2_daily_transformation_analysis.daily_transform 2022-02-19T09:25:19.936863+00:00 [queued]>
[2022-02-19 09:25:21,130] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 09:25:21,132] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2022-02-19 09:25:21,133] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-02-19 09:25:21,145] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): daily_transform> on 2022-02-19T09:25:19.936863+00:00
[2022-02-19 09:25:21,150] {standard_task_runner.py:52} INFO - Started process 424 to run task
[2022-02-19 09:25:21,156] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', '2_daily_transformation_analysis', 'daily_transform', '2022-02-19T09:25:19.936863+00:00', '--job-id', '27', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/transform_and_analysis.py', '--cfg-path', '/tmp/tmpri4xf0zv', '--error-file', '/tmp/tmpxh53rxjt']
[2022-02-19 09:25:21,159] {standard_task_runner.py:77} INFO - Job 27: Subtask daily_transform
[2022-02-19 09:25:21,225] {logging_mixin.py:104} INFO - Running <TaskInstance: 2_daily_transformation_analysis.daily_transform 2022-02-19T09:25:19.936863+00:00 [running]> on host 6f11a7de65ba
[2022-02-19 09:25:21,353] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=2_daily_transformation_analysis
AIRFLOW_CTX_TASK_ID=daily_transform
AIRFLOW_CTX_EXECUTION_DATE=2022-02-19T09:25:19.936863+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-02-19T09:25:19.936863+00:00
[2022-02-19 09:25:21,356] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-02-19 09:25:21,358] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt run --models transform --profiles-dir .']
[2022-02-19 09:25:21,373] {subprocess.py:74} INFO - Output:
[2022-02-19 09:25:23,718] {subprocess.py:78} INFO - Running with dbt=0.19.0
[2022-02-19 09:25:29,511] {subprocess.py:78} INFO - [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2022-02-19 09:25:29,516] {subprocess.py:78} INFO - There are 2 unused configuration paths:
[2022-02-19 09:25:29,520] {subprocess.py:78} INFO - - models.my_new_project.transform
[2022-02-19 09:25:29,524] {subprocess.py:78} INFO - - models.my_new_project.analysis
[2022-02-19 09:25:29,527] {subprocess.py:78} INFO - 
[2022-02-19 09:25:30,096] {subprocess.py:78} INFO - Found 7 models, 4 tests, 0 snapshots, 0 analyses, 316 macros, 0 operations, 3 seed files, 0 sources, 0 exposures
[2022-02-19 09:25:30,102] {subprocess.py:78} INFO - 
[2022-02-19 09:25:33,373] {subprocess.py:78} INFO - 09:25:33 | Concurrency: 200 threads (target='dev')
[2022-02-19 09:25:33,376] {subprocess.py:78} INFO - 09:25:33 |
[2022-02-19 09:25:33,464] {subprocess.py:78} INFO - 09:25:33 | 1 of 3 START view model public.combined_bookings..................... [RUN]
[2022-02-19 09:25:33,475] {subprocess.py:78} INFO - 09:25:33 | 2 of 3 START view model public.customer.............................. [RUN]
[2022-02-19 09:25:35,527] {subprocess.py:78} INFO - 09:25:35 | 2 of 3 OK created view model public.customer......................... [[32mSUCCESS 1[0m in 2.04s]
[2022-02-19 09:25:35,704] {subprocess.py:78} INFO - 09:25:35 | 1 of 3 OK created view model public.combined_bookings................ [[32mSUCCESS 1[0m in 2.23s]
[2022-02-19 09:25:35,720] {subprocess.py:78} INFO - 09:25:35 | 3 of 3 START view model public.prepped_data.......................... [RUN]
[2022-02-19 09:25:37,471] {subprocess.py:78} INFO - 09:25:37 | 3 of 3 OK created view model public.prepped_data..................... [[32mSUCCESS 1[0m in 1.74s]
[2022-02-19 09:25:38,673] {subprocess.py:78} INFO - 09:25:38 |
[2022-02-19 09:25:38,675] {subprocess.py:78} INFO - 09:25:38 | Finished running 3 view models in 8.57s.
[2022-02-19 09:25:38,899] {subprocess.py:78} INFO - 
[2022-02-19 09:25:38,902] {subprocess.py:78} INFO - [32mCompleted successfully[0m
[2022-02-19 09:25:38,904] {subprocess.py:78} INFO - 
[2022-02-19 09:25:38,905] {subprocess.py:78} INFO - Done. PASS=3 WARN=0 ERROR=0 SKIP=0 TOTAL=3
[2022-02-19 09:25:40,046] {subprocess.py:82} INFO - Command exited with return code 0
[2022-02-19 09:25:40,091] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=2_daily_transformation_analysis, task_id=daily_transform, execution_date=20220219T092519, start_date=20220219T092521, end_date=20220219T092540
[2022-02-19 09:25:40,135] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-02-19 09:25:40,156] {local_task_job.py:149} INFO - Task exited with return code 0
